# Generated by Django 4.2 on 2023-07-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_grand_total_alter_invoiceitems_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='balance',
            new_name='price',
        ),
    ]
