# Generated by Django 4.2 on 2023-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_debit_invoice_wallet_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='tax_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
