# Generated by Django 4.2 on 2023-10-19 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_invoiceitems_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice'),
        ),
    ]
