# Generated by Django 4.2 on 2023-11-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_wallet_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('upi', 'Upi'), ('netbanking', 'Net Banking')], max_length=10),
        ),
    ]
