# Generated by Django 4.2 on 2024-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collected_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
