# Generated by Django 4.2 on 2024-02-10 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_clinicpeople_user'),
        ('payment', '0011_payment_patient_alter_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
    ]
