# Generated by Django 4.2 on 2024-03-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_appointment_payment_status'),
        ('payment', '0014_alter_payment_invoice_alter_payment_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
