# Generated by Django 4.2 on 2024-06-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0017_payment_balance_walletpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitems',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_item_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
