# Generated by Django 4.2.13 on 2024-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_invoiceitems_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='excess_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('collected', 'Collected'), ('paid', 'Paid'), ('wallet_payment', 'Wallet')], default='collected', max_length=20),
        ),
    ]
