# Generated by Django 4.2.13 on 2024-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_invoice_is_paid_payment_excess_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('upi', 'Upi'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=10),
        ),
    ]
