# Generated by Django 4.2 on 2024-09-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_clinicpeople_user'),
        ('notification', '0003_alter_reminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
    ]
