# Generated by Django 4.2 on 2024-09-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_reminder_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
    ]
