# Generated by Django 4.2 on 2023-06-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinictiming_week_day_alter_clinic_tagline_and_more'),
        ('appointment', '0004_alter_appointment_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.clinic'),
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='tax',
        ),
        migrations.AddField(
            model_name='procedure',
            name='tax',
            field=models.ManyToManyField(blank=True, null=True, related_name='taxs', to='appointment.tax'),
        ),
    ]
