# Generated by Django 4.2 on 2023-06-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_category_clinic_procedure_clinic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdirectoryexercises',
            old_name='patient_diretory',
            new_name='patient_directory',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='previous_appointments',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='today_schedule',
        ),
    ]
