# Generated by Django 4.2 on 2023-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rename_patient_diretory_patientdirectoryexercises_patient_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='tax',
            field=models.ManyToManyField(blank=True, related_name='taxs', to='appointment.tax'),
        ),
    ]
