# Generated by Django 4.2 on 2023-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_procedure_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('engaged', 'Engaged'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('not_visited', 'Not Visited')], default='booked', max_length=20),
        ),
    ]
