# Generated by Django 4.2 on 2023-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdirectory',
            name='soap_type',
            field=models.CharField(blank=True, choices=[('subjective', 'Subjective'), ('objective', 'Objective'), ('assessment', 'Assessment'), ('procedure', 'Procedure')], max_length=20, null=True),
        ),
    ]
