# Generated by Django 4.2 on 2023-08-27 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0009_patientdirectory_soap_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdirectory',
            name='soap_type',
        ),
        migrations.AlterField(
            model_name='patientdirectory',
            name='clinical_note_type',
            field=models.CharField(choices=[('complaints', 'Chief Complaint'), ('subjective', 'Subjective'), ('objective', 'Objective'), ('assessment', 'Assessment'), ('plan', 'Plan'), ('exercises', 'Exercises')], max_length=30),
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notecategory_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notecategory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientdirectory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.notecategory'),
        ),
    ]
