# Generated by Django 4.2 on 2023-08-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_patientdirectory_soap_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
