# Generated by Django 4.2 on 2023-12-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_category_name_alter_notecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.category'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.procedure'),
        ),
    ]
