# Generated by Django 4.2 on 2023-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_appointment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial_paid', 'Partial Paid'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
