# Generated by Django 4.2.13 on 2024-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdirectory',
            name='clinical_note_type',
            field=models.CharField(choices=[('complaints', 'Chief Complaint'), ('subjective', 'Subjective'), ('objective', 'Objective'), ('assessment', 'Assessment'), ('plan', 'Plan'), ('procedure', 'Procedure'), ('exercises', 'Exercises')], max_length=30),
        ),
    ]
