# Generated by Django 4.2 on 2023-05-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slot_duration',
            field=models.CharField(choices=[('15', '15 Mins'), ('30', '30 Mins'), ('45', '45 Mins'), ('60', '1 Hour')], default='15', max_length=10),
        ),
    ]
