# Generated by Django 4.2 on 2023-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
