# Generated by Django 4.2 on 2023-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinic_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_no_1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone_no_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='beak_2_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='break_1_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='break_1_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='break_2_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinictiming',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
