# Generated by Django 4.2 on 2023-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinic_email_alter_clinic_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinictiming',
            name='week_day',
            field=models.TimeField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='tagline',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
