# Generated by Django 4.2 on 2023-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinictiming_week_day_alter_clinic_tagline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinictiming',
            old_name='beak_2_end',
            new_name='break_2_end',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
