# Generated by Django 4.2 on 2023-11-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinictiming_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='map_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='review_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
