# Generated by Django 4.2 on 2023-12-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinic_map_link_clinic_review_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicpeople',
            name='clinic',
        ),
        migrations.AddField(
            model_name='clinicpeople',
            name='clinic',
            field=models.ManyToManyField(to='clinic.clinic'),
        ),
    ]
