# Generated by Django 4.2 on 2023-12-22 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0009_remove_clinicpeople_clinic_clinicpeople_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicpeople',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
