# Generated by Django 4.2 on 2023-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_doctor_calender_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
