# Generated by Django 4.2 on 2023-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='leave_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
