# Generated by Django 4.2 on 2023-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_no_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='break_1_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='break_1_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='break_2_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='break_2_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctortiming',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
