# Generated by Django 4.2 on 2023-06-04 08:35

from django.db import migrations, models
import fuelapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_address_phone_no_1_alter_address_phone_no_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doctor_calender_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=fuelapp.validators.RestrictedImageField(blank=True, null=True, upload_to='uploads/user/', validators=[fuelapp.validators.validate_images]),
        ),
    ]
