# Generated by Django 4.2 on 2023-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_doctorleave_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortiming',
            name='week_day',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], null=True),
        ),
    ]
