# Generated by Django 4.2 on 2023-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_blood_group_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.TextField(default=None, max_length=255, null=True, verbose_name='Email Verify Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=0, verbose_name='Email Verified'),
        ),
    ]
