# Generated by Django 4.2 on 2023-08-27 18:48

from django.db import migrations
import fuelapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_email_code_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=fuelapp.validators.RestrictedImageField(blank=True, null=True, upload_to='uploads/doctor/signature/', validators=[fuelapp.validators.validate_images]),
        ),
    ]
