# Generated by Django 4.2 on 2023-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorleave',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='start_at',
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='scheduled_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='scheduled_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
