# Generated by Django 4.2 on 2023-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patient_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practo_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refferd_by',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
