# Generated by Django 4.2 on 2023-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_user_refferd_by_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by_source',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
