# Generated by Django 4.2 on 2024-02-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_rename_doctorleave_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_no_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_no_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
