# Generated by Django 4.2.13 on 2024-07-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_address_phone_no_1_alter_address_phone_no_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='practo_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
