# Generated by Django 4.2 on 2024-09-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_clinicpeople_user'),
        ('user', '0027_alter_user_atlas_id_alter_user_practo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
    ]
